name: fullbuild

on:
  push:
    branches: [ wip_fullbuild ]

jobs:
  agent_protocol_splitter:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout fog_sw
        uses: actions/checkout@v2
        with:
          path: fog_sw
          submodules: recursive

      - name: Checkout ci-scripts
        uses: actions/checkout@v2
        with:
          repository: tiiuae/fogsw-ci-scripts
          path: fogsw-ci-scripts

      - name: Run fog-sw docker build
        run: |
          set -eux
          mkdir bin
          pushd fogsw-ci-scripts
          ./generate_deb.sh ../fog_sw/agent_protocol_splitter ../bin/

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fog_sw
          path: bin/*.deb
          retention-days: 5

  fogsw_configs:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout fog_sw
        uses: actions/checkout@v2
        with:
          path: fog_sw
          submodules: recursive

      - name: Checkout ci-scripts
        uses: actions/checkout@v2
        with:
          repository: tiiuae/fogsw-ci-scripts
          path: fogsw-ci-scripts

      - name: Run fog-sw docker build
        run: |
          set -eux
          mkdir bin
          pushd fogsw-ci-scripts
          ./generate_deb.sh ../fog_sw/fogsw_configs ../bin/
          popd

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fog_sw
          path: bin/*.deb
          retention-days: 5

  fogsw_secure_os:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout fog_sw
        uses: actions/checkout@v2
        with:
          path: fog_sw
          submodules: recursive

      - name: Checkout ci-scripts
        uses: actions/checkout@v2
        with:
          repository: tiiuae/fogsw-ci-scripts
          path: fogsw-ci-scripts

      - name: Run fog-sw docker build
        run: |
          set -eux
          mkdir bin
          pushd fogsw-ci-scripts
          ./generate_deb.sh ../fog_sw/fogsw_secure_os ../bin/
          popd

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fog_sw
          path: bin/*.deb
          retention-days: 5

  mavlink-router:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout fog_sw
        uses: actions/checkout@v2
        with:
          path: fog_sw
          submodules: recursive

      - name: Checkout ci-scripts
        uses: actions/checkout@v2
        with:
          repository: tiiuae/fogsw-ci-scripts
          path: fogsw-ci-scripts

      - name: Run fog-sw docker build
        run: |
          set -eux
          mkdir bin
          pushd fogsw-ci-scripts
          ./generate_deb.sh ../fog_sw/mavlink-router ../bin/
          popd

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fog_sw
          path: bin/*.deb
          retention-days: 5

  control_interface:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout fog_sw
        uses: actions/checkout@v2
        with:
          path: fog_sw
          submodules: recursive

      - name: Checkout ci-scripts
        uses: actions/checkout@v2
        with:
          repository: tiiuae/fogsw-ci-scripts
          path: fogsw-ci-scripts

      - name: Run fog-sw docker build
        run: |
          set -eux
          mkdir bin
          pushd fogsw-ci-scripts
          ./generate_deb.sh ../fog_sw/ros2_ws/src/control_interface/ ../bin/
          popd

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fog_sw
          path: bin/*.deb
          retention-days: 5

  depthai_ctrl:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout fog_sw
        uses: actions/checkout@v2
        with:
          path: fog_sw
          submodules: recursive

      - name: Checkout ci-scripts
        uses: actions/checkout@v2
        with:
          repository: tiiuae/fogsw-ci-scripts
          path: fogsw-ci-scripts

      - name: Run fog-sw docker build
        run: |
          set -eux
          mkdir bin
          pushd fogsw-ci-scripts
          ./generate_deb.sh ../fog_sw/ros2_ws/src/depthai_ctrl ../bin/
          ./generate_deb.sh ../fog_sw/ros2_ws/src/depthai_ctrl ../bin/ host
          popd

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fog_sw
          path: bin/*.deb
          retention-days: 5

  fog_core:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout fog_sw
        uses: actions/checkout@v2
        with:
          path: fog_sw
          submodules: recursive

      - name: Checkout ci-scripts
        uses: actions/checkout@v2
        with:
          repository: tiiuae/fogsw-ci-scripts
          path: fogsw-ci-scripts

      - name: Run fog-sw docker build
        run: |
          set -eux
          mkdir bin
          pushd fogsw-ci-scripts
          export ROS=1
          ./generate_deb.sh ../fog_sw/ros2_ws/src/fog_core ../bin/
          popd

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fog_sw
          path: bin/*.deb
          retention-days: 5

  fog_msgs:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout fog_sw
        uses: actions/checkout@v2
        with:
          path: fog_sw
          submodules: recursive

      - name: Checkout ci-scripts
        uses: actions/checkout@v2
        with:
          repository: tiiuae/fogsw-ci-scripts
          path: fogsw-ci-scripts

      - name: Run fog-sw docker build
        run: |
          set -eux
          mkdir bin
          pushd fogsw-ci-scripts
          export ROS=1
          ./generate_deb.sh ../fog_sw/ros2_ws/src/fog_msgs ../bin/
          popd

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fog_sw
          path: bin/*.deb
          retention-days: 5

  indoor_pos:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout fog_sw
        uses: actions/checkout@v2
        with:
          path: fog_sw
          submodules: recursive

      - name: Checkout ci-scripts
        uses: actions/checkout@v2
        with:
          repository: tiiuae/fogsw-ci-scripts
          path: fogsw-ci-scripts

      - name: Run fog-sw docker build
        run: |
          set -eux
          mkdir bin
          pushd fogsw-ci-scripts
          ./generate_deb.sh ../fog_sw/ros2_ws/src/indoor_pos ../bin/
          popd

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fog_sw
          path: bin/*.deb
          retention-days: 5

  mesh_com:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout fog_sw
        uses: actions/checkout@v2
        with:
          path: fog_sw
          submodules: recursive

      - name: Checkout ci-scripts
        uses: actions/checkout@v2
        with:
          repository: tiiuae/fogsw-ci-scripts
          path: fogsw-ci-scripts

      - name: Run fog-sw docker build
        run: |
          set -eux
          mkdir bin
          pushd fogsw-ci-scripts
          ./generate_deb.sh ../fog_sw/ros2_ws/src/mesh_com ../bin/ modules/mesh_com/
          popd

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fog_sw
          path: bin/*.deb
          retention-days: 5

  navigation:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout fog_sw
        uses: actions/checkout@v2
        with:
          path: fog_sw
          submodules: recursive

      - name: Checkout ci-scripts
        uses: actions/checkout@v2
        with:
          repository: tiiuae/fogsw-ci-scripts
          path: fogsw-ci-scripts

      - name: Run fog-sw docker build
        run: |
          set -eux
          mkdir bin
          pushd fogsw-ci-scripts
          ./generate_deb.sh ../fog_sw/ros2_ws/src/navigation ../bin/
          popd

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fog_sw
          path: bin/*.deb
          retention-days: 5

  octomap_server2:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout fog_sw
        uses: actions/checkout@v2
        with:
          path: fog_sw
          submodules: recursive

      - name: Checkout ci-scripts
        uses: actions/checkout@v2
        with:
          repository: tiiuae/fogsw-ci-scripts
          path: fogsw-ci-scripts

      - name: Run fog-sw docker build
        run: |
          set -eux
          mkdir bin
          pushd fogsw-ci-scripts
          ./generate_deb.sh ../fog_sw/ros2_ws/src/octomap_server2 ../bin/
          popd

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fog_sw
          path: bin/*.deb
          retention-days: 5

  px4_mavlink_ctrl:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout fog_sw
        uses: actions/checkout@v2
        with:
          path: fog_sw
          submodules: recursive

      - name: Checkout ci-scripts
        uses: actions/checkout@v2
        with:
          repository: tiiuae/fogsw-ci-scripts
          path: fogsw-ci-scripts

      - name: Run fog-sw docker build
        run: |
          set -eux
          mkdir bin
          pushd fogsw-ci-scripts
          ./generate_deb.sh ../fog_sw/ros2_ws/src/px4_mavlink_ctrl ../bin/
          popd

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fog_sw
          path: bin/*.deb
          retention-days: 5

  px4_msgs:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout fog_sw
        uses: actions/checkout@v2
        with:
          path: fog_sw
          submodules: recursive

      - name: Checkout ci-scripts
        uses: actions/checkout@v2
        with:
          repository: tiiuae/fogsw-ci-scripts
          path: fogsw-ci-scripts

      - name: Run fog-sw docker build
        run: |
          set -eux
          mkdir bin
          pushd fogsw-ci-scripts
          ./generate_deb.sh ../fog_sw/ros2_ws/src/px4_msgs ../bin/
          popd

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fog_sw
          path: bin/*.deb
          retention-days: 5

  px4_ros_com:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout fog_sw
        uses: actions/checkout@v2
        with:
          path: fog_sw
          submodules: recursive

      - name: Checkout ci-scripts
        uses: actions/checkout@v2
        with:
          repository: tiiuae/fogsw-ci-scripts
          path: fogsw-ci-scripts

      - name: Run fog-sw docker build
        run: |
          set -eux
          mkdir bin
          pushd fogsw-ci-scripts
          ./generate_deb.sh ../fog_sw/ros2_ws/src/px4_ros_com ../bin/
          popd

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fog_sw
          path: bin/*.deb
          retention-days: 5

  rtl8812au:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout fog_sw
        uses: actions/checkout@v2
        with:
          path: fog_sw
          submodules: recursive

      - name: Checkout ci-scripts
        uses: actions/checkout@v2
        with:
          repository: tiiuae/fogsw-ci-scripts
          path: fogsw-ci-scripts

      - name: Run fog-sw docker build
        run: |
          set -eux
          mkdir bin
          pushd fogsw-ci-scripts
          ./generate_deb.sh ../fog_sw/rtl8812au ../bin/
          popd

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fog_sw
          path: bin/*.deb
          retention-days: 5

  systemd:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout fog_sw
        uses: actions/checkout@v2
        with:
          path: fog_sw
          submodules: recursive

      - name: Checkout ci-scripts
        uses: actions/checkout@v2
        with:
          repository: tiiuae/fogsw-ci-scripts
          path: fogsw-ci-scripts

      - name: Run fog-sw docker build
        run: |
          set -eux
          mkdir bin
          pushd fogsw-ci-scripts
          ./generate_deb.sh ../fog_sw/systemd ../bin/
          popd

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fog_sw
          path: bin/*.deb
          retention-days: 5

  fast_dds_gen:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout fog_sw
        uses: actions/checkout@v2
        with:
          path: fog_sw
          submodules: recursive

      - name: Checkout ci-scripts
        uses: actions/checkout@v2
        with:
          repository: tiiuae/fogsw-ci-scripts
          path: fogsw-ci-scripts

      - name: Run fog-sw docker build
        run: |
          set -eux
          mkdir bin
          pushd fogsw-ci-scripts
          ./generate_deb.sh ../fog_sw/tools/Fast-DDS-Gen ../bin/
          popd

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fog_sw
          path: bin/*.deb
          retention-days: 5

  libsurvive:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout fog_sw
        uses: actions/checkout@v2
        with:
          path: fog_sw
          submodules: recursive

      - name: Checkout ci-scripts
        uses: actions/checkout@v2
        with:
          repository: tiiuae/fogsw-ci-scripts
          path: fogsw-ci-scripts

      - name: Run fog-sw docker build
        run: |
          set -eux
          mkdir bin
          pushd fogsw-ci-scripts
          ./generate_deb.sh ../fog_sw/tools/libsurvive ../bin/
          popd

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: fog_sw
          path: bin/*.deb
          retention-days: 5

  basic_acceptance_test:
    runs-on: ubuntu-latest
    needs:
      - agent_protocol_splitter
      - fogsw_configs
      - fogsw_secure_os
      - mavlink-router
      - control_interface
      - depthai_ctrl
      - fog_core
      - fog_msgs
      - indoor_pos
      - mesh_com
      - navigation
      - octomap_server2
      - px4_mavlink_ctrl
      - px4_msgs
      - px4_ros_com
      - rtl8812au
      - systemd
      - fast_dds_gen
      - libsurvive
    steps:

      - name: Get artifacts
        uses: actions/download-artifact@v2
        with:
          name: fog_sw
          path: bin

      - name: testing
        run: |
          echo "hello!"
          ls -l
          ls -l bin/
